### ISSUE TITLE
Remove Femah.TestWebApp out in to a separate repo/solution/NuGet packge

### ISSUE THREAD

**Issue by lholman** [lloydstone/femah#12]
Before packaging up Femah.Core as a tasty little NuGet package we should remove Femah.TestWebApp, should we create lloydstone/Femah.TestWebApp which consumes the Femah.Core NuGet package and wrap that up as its own NuGet package later down the line?

**Comment by hotstone** [comment]
Yep, that makes sense!

**Comment by lholman** [comment]
This is now complete https://github.com/lloydstone/femah.examples now contains the WebApp example minus Femah references which need to be added back in once we have a NuGet package.
