### ISSUE TITLE
Rename the FeatureSwitching class to include the Femah in the name?

### ISSUE THREAD

**Issue by lholman** [lloydstone/femah#14]
Looking over the documentation again, in particular when using Femah https://github.com/lloydstone/femah#3-add-conditional-logic-within-your-web-application-to-use-feature-switches we seem to be inconsistent with our naming.

Would it be more intuitive for 

`FeatureSwitching.IsFeatureOn`

to become

`Femah.IsFeatureOn`

Thoughts??

**Comment by hotstone** [comment]
Agreed - I had actually been wondering the same thing previously.
