### ISSUE TITLE
API integration to support Admin UI and basic use cases

### ISSUE THREAD

**Issue by lholman** [lloydstone/femah#24]
**Services**
- [x] GET all Feature Switches `FeatureSwitching.AllFeatures()` - e.g GET: http://example.com/femah.axd/api/featureswitches
- [x] GET all Feature Switch Types `FeatureSwitching.AllSwitchTypes()` - e.g. GET: http://example.com/femah.axd/api/featureswitchtypes

**Parameters**
- [x] GET a single Feature Switch with its associated Feature Switch Type `FeatureSwitching.GetFeature()` - e.g. GET: http://example.com/femah.axd/api/featureswitch/improvedcheckout 
- [x] PUT (Update) a single Feature Switch (IsEnabled, SetCustomAttributes, FeatureType) - e.g. PUT: http://example.com/femah.axd/api/featureswitch/improvedcheckout

**Comment by lholman** [comment]
@hotstone Would you say the above covers it for the API, to both drive the UI and for MVP?

**Comment by hotstone** [comment]
Yep, that looks like everything.

**Comment by lholman** [comment]
Completed, to the best of my knowledge, with suitable test coverage.  Implementing #5 will likely raise some issues which we can deal with.
