### ISSUE TITLE
Should Feature Switch types contain a description?

### ISSUE THREAD

**Issue by lholman** [lloydstone/femah#33]
I'm feeling that merely returning Feature Switch types as `List<Type>` from the API is a bit too limited, I'd like to be able to return some basic metadata such as a human readable description (think of the class summary in the PercentageFeatureSwitch) and admin UI configuration instructions, as well, maybe as a strongly typed list too, thoughts?

**Comment by lholman** [comment]
Assigned to you for comment pleasey!

**Comment by hotstone** [comment]
That's a very good point - I'd definitely agree that feature switch types need to contain some sort of description!    Maybe some public properties on the interface?

Eg.

```
string Description { get; set; }
string ConfigurationInstructions {get;set;}
```

What do you mean by a strongly typed list too?

**Comment by lholman** [comment]
Do you mean properties on FeatureSwitchBase ?

```
namespace Femah.Core.FeatureSwitchTypes
{
    /// <summary>
    /// A generic base class, implementing default behaviour for the IFeatureSwitch interface.
    /// </summary>
    public abstract class FeatureSwitchBase : IFeatureSwitch
    {
        /// <summary>
        /// Is the feature switch enabled.
        /// </summary>
        public virtual bool IsEnabled { get; set; }

        /// <summary>
        /// The name of the feature switch.
        /// </summary>
        public virtual string Name { get; set; }

        public virtual string Description {get;}
        public virtual string ConfigurationInstructions {get;}
```

**Comment by hotstone** [comment]
I meant on the IFeatureSwitch interface, so that it then becomes a responsibility of any implementors to include that:

```
namespace Femah.Core
{
    public interface IFeatureSwitch
    {
      ...
      public string Description { get; }
      public string ConfigurationInstructions { get; }
    }
}
```

Although if we also put default implementations in the FeatureSwitchBase that would make it simpler for anyone to implement their own types:

```
public abstract class FeatureSwitchBase : IFeatureSwitch
{
   ....
   public virtual string Description { return "A feature switch"; }
   public virtual string ConfigurationInstructions { return "Nothing here."; }
```

But this would mean a lot of times those properties aren't overriden, so in that sense it would be better to not provide default implementations and instead force the implementor to provide them.

**Comment by lholman** [comment]
So my implementation for PercentageFeatureSwitch may be something like this do you mean?

```
public class PercentageFeatureSwitch : FeatureSwitchBase
    {
       ....
       public string Description { return "A simple feature switch that is on for a set percentage of users. The state of the switch is persisted in the user's cookies.If no cookie exists the state is chosen at random (weighted according to the percentage), and then stored in a cookie."; }

      public string ConfigurationInstructions { return "Set PercentageOn to the percentage of users who should see this feature. Eg. 10 means the feature is on for 10% of users."; }

```

**Comment by hotstone** [comment]
Yep, exactly!

**Comment by lholman** [comment]
I like that, no persistence required elsewhere.  
So, kind of related to #32, when returning the FeatureSwitch types from the API, it will no longer be sufficient to return a JSON'ified `List<Type>`, should we return a new custom type instead, such as?

```
namespace Femah.Core.Api
{
    public class ApiFeatureSwitchType
    {
        public string Name { get; set; }
        public Type FeatureSwitchType { get; set; }
        public string Description { get; set; }
        public string ConfigurationInstructions { get; set; }
    }
}
```

We can then return `List<ApiFeatureSwitchType>` which will allow the UI to render the Name and Description and ConfigurationInstructions nicely?

**Comment by hotstone** [comment]
I don't mind if we do that, although I'm not sure why we couldn't return `List<IFeatureSwitch>`?  Would it not serialize to JSON correctly?

**Comment by hotstone** [comment]
Ignore me - you're completely right.  We need a type that describes a feature switch type (include description, name, configuration text) etc.  Your `ApiFeatureSwitchType` looks perfect, I'd say.
