### ISSUE TITLE
Lower required version of .NET.

### ISSUE THREAD

**Issue by hotstone** [lloydstone/femah#38]
Femah currently requires .NET 4.5 at least (I think).  We want to be able to support as wide a variety of consuming applications as possible, so we need to get this down to the minimum possible version.

**Comment by lholman** [comment]
- An interesting stackoverflow question about producing a Nuget package that targets multiple .NET framework versions http://stackoverflow.com/questions/12867495/multi-framework-nuget-build-with-symbols-for-internal-dependency-management

**Comment by lholman** [comment]
So, after a bit of research combined with some common sense, we have a few options here:

### 1. Support all significant .NET framework versions from 2.0 upwards by targeting a build for each framework.

This is relatively simple to get started with (detail here: http://alandean.blogspot.co.uk/2011/02/framework-version-targeting-with.html), allowing us to then do the following as part of the build.

`C:\>msbuild Femah.sln /p:Configuration=Release /p:TargetFrameworkVersion=v2.0
C:\>msbuild Femah.sln /p:Configuration=Release /p:TargetFrameworkVersion=v3.0
C:\>msbuild Femah.sln /p:Configuration=Release /p:TargetFrameworkVersion=v3.5
C:\>msbuild Femah.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.0
C:\>msbuild Femah.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.5`

resulting in..

![femah_issue38_physicalbuildoutput_option1](https://f.cloud.github.com/assets/362197/2168951/5c30edca-954f-11e3-8df1-b439247eba13.PNG)

Hold your horses though, it isn't really that simple, think about all the framework references we have in `Femah.Core.csproj` and `Femah.Core.Tests.csproj`, yep they're framework specific, so we get an absolute tonne of warnings, 135 to be precise, an example below using the following msbuild command..

`C:\>msbuild Femah.sln /p:Configuration=Release /p:TargetFrameworkVersion=v2.0`

![femah_issue38_consolebuildoutput_option1](https://f.cloud.github.com/assets/362197/2168953/64e43c6a-954f-11e3-9614-87d3eafeda4d.PNG)

Spot all the "has a higher version "4.0.0.0" than the version "2.0.0.0" in the current target framework"?  Surprisingly it does build `Femah.Core.dll`
But wait, Femah.Core.dll is identical for .NET 2.0 and .NET 4.5

![femah_issue38_identicalassemblies_options1](https://f.cloud.github.com/assets/362197/2168955/6e4c0e0e-954f-11e3-8b8d-fc31a4a35bb0.PNG)

I'm struggling to understand what the hell msbuild is doing to build that `Femah.Core.dll` assembly though, failing back to the default `<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>` in the csproj file I expect?  I'd really prefer it to blow up with all those reference "warnings" being genuine "errors" instead.

So firing up ilspy using `cinst ilspy` shows us the following for the supposed NET20 (.NET 2.0) assembly 

![femah_issue38_net20assemblynotnet20_ilspy_options1](https://f.cloud.github.com/assets/362197/2168956/754931be-954f-11e3-9c94-c60aaac59415.PNG)

yep, it's building using the .NET 4.0 runtime (I assume it reports 4.0 as 4.5 was an in-place upgrade of 4.0 #facepalm)

Furthermore, as you'd expect `Newtonsoft.Json.dll` isn't copied to the \BuildOutput (aka \bin) folder (see below). 

![femah_issue38_buildoutputmissingdependencies_options1](https://f.cloud.github.com/assets/362197/2168961/7b2fd22c-954f-11e3-97b7-bdc096347ece.PNG)

#### Option 1. Summary

To get around all the above it's possible to conditionally load different assembly reference versions (framework and external), but I can only imagine that getting messy really quickly.

**Comment by lholman** [comment]
### Option 2. Support all significant .NET framework versions from 2.0 upwards by producing a project file for each version

A way of reducing the conditional logic within a single project implementation (as detailed above in option 1) is to utilise multiple solution (.sln) and project (.csproj) files, as follows..

```
FemahNET20.sln
    Femah.Core.NET20.csproj
    Femah.Core.Tests.NET20.csproj
FemahNET30.sln
    Femah.Core.NET30.csproj
    Femah.Core.Tests.NET30.csproj
FemahNET35.sln
    Femah.Core.NET35.csproj
    Femah.Core.Tests.NET35.csproj
FemahNET40.sln
    Femah.Core.NET40.csproj
    Femah.Core.Tests.NET40.csproj
FemahNET45.sln
    Femah.Core.NET45.csproj
    Femah.Core.Tests.NET45.csproj
```

It is important to note the following:
- Each project contains references only to the .NET framework version it is explicitly targeting.
- Each project contains common class files and assets (utilising file linking in Visual Studio), with gradually more of the implementation appearing in later frameworks.
- A certain level of conditional compile time constant usage may still be required, depending on architecture.

A build would then compile each solution individually, producing a relevant `\BuildOutput\NETxx` folder.  A separate build task would then reference the appropriate .nupsec file, combining all assemblies in to an appropriate .nupkg Nuget package.

It is worth noting that this is the approach used by JSON.NET (http://james.newtonking.com/json)

#### Option 2. Summary

@hotstone and I are in agreement that this option at present is not necessary for Femah.  We are in the early days of Femah and are not sure if there will be uptake, let alone whether that uptake will be enough to justify the overhead of building out the complex approach above, or indeed mentioned in Option 1, both of which will undoubtedly introduce significant effort.

### Option 3. Keep it simple and target .NET framework 3.5 only

The title says it all.  @hotstone and I feel that simply targeting the compilation of femah to .NET framework version 3.5 will realise the following benefits...
- Keeps the project configuration and build simple (one solution and one project file per project).
- Ensures compatibility with all .NET frameworks from 3.5 upwards (4.0 and 4.5+).
- Allows femah to continue utilising the bulk of really useful .NET framework and C# language capabilities, without having to re-work for .NET 2.0.
- Gives us flexibility to introduce Options 1 or 2 at a later stage, if the desire and uptake demands it.

It is worth noting that this is the approach used by Elmah (https://code.google.com/p/elmah/) and Shouldly (http://shouldly.github.io/)

Decision, utilise Option 3.
