### ISSUE TITLE
Generate github releases pro-grammatically as nuget package is published

### ISSUE THREAD

**Issue by lholman** [lloydstone/femah#41]
It'd be nice (post MVP) to generate a formal Github release with every package we push to nuget.org, kind of like here https://github.com/loresoft/msbuildtasks/releases and here https://github.com/JamesNK/Newtonsoft.Json/releases

Github documentation is here https://github.com/blog/1547-release-your-software and API docs here http://developer.github.com/v3/repos/releases/#create-a-release

That is all.

**Comment by hotstone** [comment]
This looks very nice.  Can't wait to play with it.

**Comment by lholman** [comment]
This kind of suggests the opposite of what we're proposing in issue #48, i.e. github releases are where we begin with a release, as opposed to being generated post nuget packaging and pushing (as suggested here).  For that reason I'm closing this issue, #48 is king now.
