### ISSUE TITLE
Kill your hotstone/femah.examples fork to avoid confusion pleasey

### ISSUE THREAD

**Issue by lholman** [lloydstone/femah#66]
As we agreed, I'd like to try and commit directly to femah.examples as a shared repository, still using pull requests from "feature" branches, god I hate that term, from "descriptive short lived" branches, see I've done it here.

https://github.com/lloydstone/femah.examples/network

So kill the below if you don't mind, so as to avoid confusion, I'll then talk you through how it works, but fundamentally it follows this too #65, just a few less steps. 

![githubkillfemahexamplesfork](https://cloud.githubusercontent.com/assets/362197/2597394/a2a5d494-bab3-11e3-87c2-141e7510d5f9.PNG)

**Comment by hotstone** [comment]
Done!
