### ISSUE TITLE
Do we trust the SqlProvider, get some tests around it.

### ISSUE THREAD

**Issue by lholman** [lloydstone/femah#96]
We have no real confidence that the SqlProvider works as expected, what can we do for this?

**Comment by AwaNoodle** [comment]
Can the SQL Provider be moved out to a separate nuget package so that we can produce a EF6 Provider or a Simple.Data Provider? Having this separate keeps the dependencies out of Femah and lets us build some realistic implementations.

**Comment by lholman** [comment]
@AwaNoodle I agree this would be a great approach, as we discussed in the pub.  However, apologies if the following doesn't reflect everything we mentioned, I've had time to look at it now and have a slightly different take on it in retrospect :(.
I'm not sold on EF if I'm honest, would prefer something more light weight, only if the current implementation doesn't cut it.  That said having a good look @hotstone has implemented this in a very light weight way with `SqlConnection` and `SqlCommand`, although we do have "todo's" for 
- ///TODO: Autogenerate table when it doesn't exist.
- /// TODO: Allow consumer to override table & column names.

But yes pulling it out to a `femah.sql` nuget package that depends on `femah.core` sounds like a sound idea. Thinking pragmaticly maybe it should go something like this.

For MVP
- [ ] Get some unit testing in place (as per the subject), we need confidence around this provider.
- [ ] Update https://github.com/lloydstone/femah/readme.md and/or http://lloydstone.github.io/femah/ with documentation about how to use it.
- [ ] Provide SQL script for generating schema, or optionally look at a simple db schema management solution such as RoundHouse?

Post MVP
- [ ] Extract `Femah.Core.Providers.SqlServerProvider` out of https://github.com/lloydstone/femah in to a separate repo (with any supporting scripts and documentation).
- [ ] Create the deployment pipeline for a `femah.sql` nuget package that depends on `femah.core`
- [ ] Refactor if required to solve the above TODO's and a light weight data access layer, but only if truly required.

@hotstone @AwaNoodle thoughts?

**Comment by hotstone** [comment]
@lholman 
Yep, the SqlProvider was meant to be as lightweight as possible, hence the use of SqlConnection directly rather than any ORM layer.   For that same reason, I don't know if using RoundhousE to generate the table would be the best solution.

I'd agree that, post-mvp, we should break out non-core parts of Femah into separate packages to reduce dependencies in the core.  Web-specific parts for example, such as the API and UI, should really be in a separate package too since they're not part of the core functionality of Femah.

**Comment by lholman** [comment]
@hotstone Yeah, I thought as much. I think RoundHouse or something similar for managing db schema would be acceptable if we break it out in to another package.

We did speak about API and UI being split out sometime back, agree but wonder really if anyone would ever use femah.core without the UI and API, seems a bit pointless?

Regardless, are you happy with the three things we need to do for MVP, if so I'll create them as separate issues, anything I've missed?
- [ ] Get some unit testing in place (as per the subject), we need confidence around this provider.
- [ ] Update https://github.com/lloydstone/femah/readme.md and/or http://lloydstone.github.io/femah/ with documentation about how to use it.
- [ ] Provide SQL script for generating schema, or optionally look at a simple db schema management solution such as RoundHouse?

**Comment by hotstone** [comment]
@lholman I disagree with regards to it being pointless - for use in a WinForms app, etc., there's no logical reason to include a UI/API.  

Happy with the others, although for the third I'd scratch the RoundhousE comment.

**Comment by lholman** [comment]
@hotstone Ahhh that's a really valid point about Winforms apps, services etc, completely slipped my mind, I'll open another issue about that, I think it needs some thought now, i.e. nuget package names, dependencies moving forward etc.

With regards to the points above, will get them created as issues.

**Comment by lholman** [comment]
Ok, I've created #99, #100, #101 and #102 to cover these points of, so this issue can now be closed.
